export const COUNTRIES: { name: string; locations: string[] }[] = [
  {
    name: "India",
    locations: [
      "Delhi",
      "Mumbai",
      "Bengaluru",
      "Hyderabad",
      "Chennai",
      "Pune",
      "Kolkata",
      "Ahmedabad",
      "Jaipur",
      "Lucknow",
      "Chandigarh",
      "Indore",
      "Kochi",
      "Surat",
      "Noida",
    ],
  },
  {
    name: "United States",
    locations: [
      "New York",
      "Los Angeles",
      "Chicago",
      "Houston",
      "Phoenix",
      "Miami",
      "Dallas",
      "Seattle",
      "Atlanta",
      "Boston",
    ],
  },
  {
    name: "United Kingdom",
    locations: ["London", "Manchester", "Birmingham", "Leeds", "Glasgow", "Liverpool"],
  },
  {
    name: "Canada",
    locations: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa"],
  },
  {
    name: "Australia",
    locations: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
  },
  {
    name: "United Arab Emirates",
    locations: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman"],
  },
];

export const BUSINESS_TYPES = [
  "Restaurant",
  "Cafe",
  "Gym",
  "Salon",
  "Spa",
  "Dentist",
  "Doctor / Clinic",
  "Real Estate Agent",
  "Plumber",
  "Electrician",
  "Car Repair",
  "Hotel",
  "Boutique",
  "Bakery",
  "Photographer",
  "Interior Designer",
  "Tuition Center",
  "Pet Store",
];
